### ISSUE TITLE
Rechercher une musique, un livre ou un film

### ISSUE THREAD

**Issue by manantsoa** [iMoTeam/IMoGRAM#5]
_En tant que_ Utilisateur
_Je souhaite_ rechercher un livre, une musique ou un film
_Afin de_ voir les résultats de ma recherche

**Comment by Veoth** [comment]
Il faudrait que tu push un jour, sans quoi c'est compliqué de savoir ce qu'il a été fait.

**Comment by manantsoa** [comment]
:+1: @Veoth :) @WeDemBoyz  mais aussi @yanxkz n'hésitez pas à pusher ça coûte rien et c'est gratuit ! Et ça permet à tout le monde de voir votre avancement ;)
